apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-staging
bases:
  - ../../base
patchesStrategicMerge:
  - patch.yaml
patchesJson6902:
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: Gateway
    name: app-gateway
  path: app-gateway.yaml
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: VirtualService
    name: app-vs
  path: app-vs.yaml
