apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api-staging
bases:
  - ../../base
patchesJson6902:
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: Gateway
    name: api-gateway
  path: api-gateway.yaml
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: VirtualService
    name: api-vs
  path: api-vs.yaml
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: Gateway
    name: app-gateway
  path: app-gateway.yaml
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: VirtualService
    name: app-vs
  path: app-vs.yaml
