apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-staging
nameSuffix: -staging
bases:
  - ../../base
patchesStrategicMerge:
  - patch.yaml
patches:
  - app-gateway.yaml
  - app-vs.yaml
