apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app.kubernetes.io/name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      volumes:
          - name: config-volume
            configMap:
              name: app-configmap
      containers:
      - name: app
        image: 904573531492.dkr.ecr.eu-central-1.amazonaws.com/app:f972a07
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/js/config.js
          subPath: config.js
