apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-deployment
  labels:
    app.kubernetes.io/name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: app
        image: 904573531492.dkr.ecr.eu-central-1.amazonaws.com/app:0.9.2
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
  strategy:
    canary:
      canaryService: app-service-canary
      stableService: app-service
      trafficRouting:
        istio:
           virtualService: 
            name: app-vs
            routes:
            - main
