apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-vs
spec:
  hosts:
  - app-test.rabegitops.it
  gateways:
  - app-gateway
  http:
  - name: main
    route:
    - destination:
        host: app-service
        port:
          number: 8080